msg-node-nodejs:
    image: msg-node-nodejs:latest
    # to build msg-node-nodejs manually use command: sudo docker build -t msg-node-nodejs .
    # For Easy Development of the msg-node load this volume
    # volumes:
    #     - /path/to/msg-node/repository:/usr/src/app
    ports:
        - "9090:9090"
    environment:
        - url=localhost  # url:domain of CSP where the Messaging Node would be deployed
        - port=9090     # port:port of Messaging Node would be deployed
        - domainRegistryUrl=http://localhost:4567/ # url:domain of CSP where the registry-domain would be deployed or domainRegistryUrl=http://172.18.0.4:4567/
        - globalRegistryUrl=http://130.149.22.133:5002/ # url:domain of CSP where the Global Registry would be deployed
        - logLevel=INFO
        # - logDir=/usr/src/app/logs
        # - useSSL=1
        # - sslCertificate=/usr/src/app/src/ssl/myCert.crt
        # - sslPKey=/usr/src/app/src/ssl/myCert.key

registry-domain:
    image: rethink/registry-domain-server:latest
    ports:
        - "4567:4567"
    environment:
        - STORAGE_TYPE=RAM
        - EXPIRES=3600
